version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/theme-src"
    schedule:
      interval: weekly
    assignees:
      - kai687
    groups:
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - kai687
    groups:
      uv-packages:
        patterns:
          - "*"
        exclude-patterns:
          - "docutils"
          - "sphinx"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - kai687
