version: 2
updates:
  - package-ecosystem: npm
    directory: "/src/theme-src"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    assignees:
      - kai687
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    assignees:
      - kai687
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    assignees:
      - kai687
